services:

  redis-service:
    image: redis:alpine
    container_name: redis-broker
    volumes:
      - ./redis-volume:/data

  webhook-extensions-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: extension_server_example
    environment:
      - PORT=8083
    restart: always

  coturn-service:
    image: coturn/coturn
    container_name: coturn
    volumes:
      - ./coturn-config:/etc/turnserver
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    restart: always

  broker-service-1:
    image: crolangp2p/broker
    container_name: broker-1
    depends_on:
      - redis-service
      - webhook-extensions-server
      - coturn-service
    environment:
      - PORT=8081
      - LOG_LEVEL=2
      - REDIS_URL=redis://redis-service:6379
      - RTC_CONFIGURATION_RESOLVER_WEBHOOK_URL=http://webhook-extensions-server:8083/resolve-rtc-configuration
      - NODES_AUTHENTICATION_WEBHOOK_URL=http://webhook-extensions-server:8083/authenticate-node
      - AUTHORIZE_NODES_COMMUNICATION_WEBHOOK_URL=http://webhook-extensions-server:8083/authorize-nodes-communication
      - NODES_VALIDITY_CHECK_WEBHOOK_URL=http://webhook-extensions-server:8083/validity-check
      - ON_AUTHENTICATED_SOCKET_MSG_WEBHOOK_URL=http://webhook-extensions-server:8083/authenticated-socket-msg

  broker-service-2:
    image: crolangp2p/broker
    container_name: broker-2
    depends_on:
      - redis-service
      - webhook-extensions-server
      - coturn-service
    environment:
      - PORT=8082
      - LOG_LEVEL=2
      - REDIS_URL=redis://redis-service:6379
      - RTC_CONFIGURATION_RESOLVER_WEBHOOK_URL=http://webhook-extensions-server:8083/resolve-rtc-configuration
      - NODES_AUTHENTICATION_WEBHOOK_URL=http://webhook-extensions-server:8083/authenticate-node
      - AUTHORIZE_NODES_COMMUNICATION_WEBHOOK_URL=http://webhook-extensions-server:8083/authorize-nodes-communication
      - NODES_VALIDITY_CHECK_WEBHOOK_URL=http://webhook-extensions-server:8083/validity-check
      - ON_AUTHENTICATED_SOCKET_MSG_WEBHOOK_URL=http://webhook-extensions-server:8083/authenticated-socket-msg

  haproxy-service:
    image: haproxy
    container_name: haproxy-broker
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy
    depends_on:
      - broker-service-1
      - broker-service-2
